name: snapclick
description: "A event management application that helps users organize their daily activities and track days to given date."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  sqflite: ^2.4.1
  path: ^1.9.0
  provider: ^6.1.2
  awesome_notifications: ^0.10.1
  http: ^1.3.0
  uuid: ^4.3.3 # Added for generating unique IDs
  shared_preferences: ^2.3.0 # Added for storing notification settings
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true